# commit to be tagged for the new release
commit = "HEAD"

project_name = "bldr"
github_repo = "siderolabs/bldr"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v0.2.1"
pre_release = false

# [notes]
